Symlink
hiqdev/hidev pull request #6
Opened 2018-11-15 18:01 UTC by jomonkj

2018-11-15 18:10 UTC, jomonkj commented
consider if it run from docker.
will produce 
```ssh
bash: sudo: command not found
```
 i removed sudo.

https://github.com/hiqdev/hidev/blob/master/src/helpers/FileHelper.php#L104

2018-11-15 18:15 UTC, hiqsol requested changes

2018-11-15 18:15 UTC, hiqsol commented on src/components/Directory.php
> +            } elseif (isset($config['dest'])) {
Please rename dest -> symlink

2018-11-15 18:15 UTC, hiqsol commented on src/components/Symlink.php
> +use hidev\base\File as FileObj;
Remove unused `use`s.

2018-11-15 18:15 UTC, hiqsol commented on src/components/Symlink.php
> +    public $dest;
dest -> symlink

2018-11-15 18:16 UTC, hiqsol commented
Does it do what you need?

2018-11-17 15:08 UTC, jomonkj commented
working but showing an error like
```
Couldn't read file: ./public/admin/media
```

2018-11-22 14:00 UTC, jomonkj commented
waiting for merge :smile:

2018-11-23 07:24 UTC, hiqsol requested changes

2018-11-23 07:24 UTC, hiqsol commented on src/helpers/FileHelper.php
> +                unlink($dst);
this is not efficient
better readlink and compare with desired dst and then delete or do nothing

2018-11-25 15:58 UTC, jomonkj commented
Done :smile:

2018-11-25 16:13 UTC, merged